BankingSystem v1.0
MaksimKosyanchuk/-DICT_python_education_Maksim_Kosyanchuk pull request #51
Opened 2023-04-28 17:44 UTC by MaksimKosyanchuk

2023-04-30 13:26 UTC, PopovDev requested changes
Вместо pylint: disable=too-few-public-methods используй dataclass

2023-05-01 06:59 UTC, MaksimKosyanchuk commented
По типу интерфейса заюзать? А на него он не будет жаловаться?

2023-05-01 07:01 UTC, MaksimKosyanchuk commented
> Вместо pylint: disable=too-few-public-methods используй dataclass

По типу интерфейса заюзать? А на него он не будет жаловаться?

2023-05-02 15:55 UTC, ViA-RiVaL commented on banking_system/account.py
> +class Account:
Используйте dataclass.

2023-05-02 15:56 UTC, ViA-RiVaL commented on banking_system/account.py
> +class TryLogin:
Тут тоже dataclass.

2023-05-02 18:31 UTC, MaksimKosyanchuk commented
> > В классе BankingServices все методы статические. Каков в этом смысл?
> 
> Есть класс, который просто имеет набор методов, которые я вызываю с другого класса, статические методы т.к. не нуждается в создании экземпляра класса, сделано чтоб разбить код, в banking_system.py только приветствие и основной цикл программы, в banking_services.py вся логика взаимодействия с пользователем, database.py имеет методы для работы с базой данных

2023-05-05 08:10 UTC, ViA-RiVaL approved these changes

2023-05-10 18:33 UTC, merged